export type FacebookAdCreative = {
  id: string;
  name: string;
  audience: string;
  angle: string;
  eyebrow: string;
  headline: string[];
  supportingText: string;
  image: "/images/marketing-design-1.png" | "/images/marketing-design-2.png" | "/images/marketing-design-3.png" | "/images/marketing-hero.png";
  primaryText: string;
  linkHeadline: string;
  description: string;
  cta: "Learn More" | "Sign Up";
  variant: "phone" | "split" | "statement" | "free-offer" | "one-link" | "browser" | "checklist" | "before-after" | "question" | "text-only" | "text-only-coach";
  series?: "parent" | "simple";
};

export const facebookAdCreatives: FacebookAdCreative[] = [
  {
    id: "parent-seven-places",
    name: "Seven places → one link",
    audience: "Parents of high-school baseball players",
    angle: "Organization",
    eyebrow: "MAKE RECRUITING EASIER TO MANAGE",
    headline: ["Their recruiting info", "shouldn't live in", "seven places."],
    supportingText: "Film, stats, academics, contact information, and their story—organized in one polished link.",
    image: "/images/marketing-hero.png",
    primaryText: "Film in one app. Stats in a spreadsheet. Academic details in an email. When someone asks about your player, pulling everything together should not become another project. Diamond Profile gives baseball families one polished, current link for the full player story.",
    linkHeadline: "Give their work one place to live",
    description: "Build a baseball recruiting website in minutes.",
    cta: "Learn More",
    variant: "phone",
  },
  {
    id: "parent-coach-asks",
    name: "When a coach asks",
    audience: "Parents actively navigating recruiting",
    angle: "Readiness",
    eyebrow: "BE READY FOR THE NEXT CONVERSATION",
    headline: ["When a coach asks", "for film—what do", "you send?"],
    supportingText: "One link can give them the film and the context around the player.",
    image: "/images/marketing-design-1.png",
    primaryText: "A video link alone does not tell the whole story. Give coaches one clear place to view film, stats, academics, schedule, contact information, and the athlete behind it all.",
    linkHeadline: "One link. The complete player.",
    description: "Start a Diamond Profile free.",
    cta: "Sign Up",
    variant: "split",
  },
  {
    id: "parent-first-impression",
    name: "A stronger first impression",
    audience: "Parents of serious student-athletes",
    angle: "Presentation",
    eyebrow: "THE WORK DESERVES A BETTER PRESENTATION",
    headline: ["They've put in", "the work."],
    supportingText: "Help them present it with the same level of care.",
    image: "/images/marketing-design-3.png",
    primaryText: "Years of practices, games, academics, and development should not be reduced to a scattered group of links. Diamond Profile turns the work your athlete has already done into one clear, professional recruiting website.",
    linkHeadline: "Present the whole player",
    description: "Film, stats, academics, story, and more.",
    cta: "Learn More",
    variant: "statement",
  },
  {
    id: "parent-less-chaos",
    name: "Less recruiting chaos",
    audience: "Busy baseball parents",
    angle: "Simplicity",
    eyebrow: "A SIMPLER SYSTEM FOR BASEBALL FAMILIES",
    headline: ["Less searching.", "Less resending.", "One current link."],
    supportingText: "Update the profile once. Keep sharing the same address.",
    image: "/images/marketing-design-2.png",
    primaryText: "Recruiting already comes with enough moving parts. Keep your athlete's important information organized in one place, update it as the season changes, and share the same link every time.",
    linkHeadline: "Make the process easier to manage",
    description: "Create their profile today.",
    cta: "Sign Up",
    variant: "split",
  },
  {
    id: "parent-phone-test",
    name: "The phone test",
    audience: "Parents reviewing recruiting materials",
    angle: "Mobile clarity",
    eyebrow: "TRY THIS 30-SECOND PROFILE TEST",
    headline: ["Can someone find", "the essentials", "from their phone?"],
    supportingText: "Film. Position. Graduation year. Academics. Contact. No digging required.",
    image: "/images/marketing-hero.png",
    primaryText: "Open your athlete's recruiting information from a phone and time how long it takes to find the essentials. Diamond Profile is designed to make the important details easy to scan, watch, and share from one link.",
    linkHeadline: "Make every visit easy to navigate",
    description: "See what a complete profile can look like.",
    cta: "Learn More",
    variant: "phone",
  },
  {
    id: "program-every-player",
    name: "Every player, presented well",
    audience: "Travel coaches and program directors",
    angle: "Team-wide consistency",
    eyebrow: "FOR CLUBS, ACADEMIES, AND PROGRAMS",
    headline: ["Give every player", "a recruiting presence", "you can stand behind."],
    supportingText: "Consistent profiles. Easier management. A better experience for families.",
    image: "/images/marketing-design-3.png",
    primaryText: "Your program develops the players. Diamond Profile helps you present them. Create and manage polished player websites with consistent structure, optional white-label branding, and one clear experience for every family.",
    linkHeadline: "A better profile system for your program",
    description: "Explore partner and white-label options.",
    cta: "Learn More",
    variant: "statement",
  },
  {
    id: "simple-free-baseball-site",
    name: "Make a free baseball website",
    audience: "Parents and high-school baseball families",
    angle: "Free offer",
    eyebrow: "START FREE",
    headline: ["Make a free", "baseball portfolio", "website."],
    supportingText: "Film, stats, academics, contact information, and more in one link.",
    image: "/images/marketing-design-1.png",
    primaryText: "Make a free website for your baseball player. Put their film, stats, academics, contact information, and story in one link.",
    linkHeadline: "Build a free baseball portfolio",
    description: "Create and publish with Diamond Profile.",
    cta: "Sign Up",
    variant: "free-offer",
    series: "simple",
  },
  {
    id: "simple-better-profile-free",
    name: "Build a better profile—free",
    audience: "Parents of high-school baseball players",
    angle: "Pure offer",
    eyebrow: "DIAMOND PROFILE",
    headline: ["Build a better", "baseball recruiting", "profile."],
    supportingText: "Film, stats, academics, and story. One link.",
    image: "/images/marketing-design-1.png",
    primaryText: "Build a better baseball recruiting profile. Bring film, stats, academics, and the player's story together in one link—free.",
    linkHeadline: "Build their profile free",
    description: "The whole player. One link.",
    cta: "Sign Up",
    variant: "text-only",
    series: "simple",
  },
  {
    id: "simple-easy-for-coaches",
    name: "Easy for coaches to scan",
    audience: "Parents focused on clear recruiting presentation",
    angle: "Coach clarity",
    eyebrow: "ONE CLEAR RECRUITING LINK",
    headline: ["Make it easy", "for coaches to see", "the whole player."],
    supportingText: "Film, stats, academics, schedule, and contact information—one clear link.",
    image: "/images/marketing-design-2.png",
    primaryText: "Make it easy for coaches to see the whole player. Put film, stats, academics, schedule, and contact information in one clear link.",
    linkHeadline: "Give coaches the full picture",
    description: "Build their baseball profile free.",
    cta: "Sign Up",
    variant: "text-only-coach",
    series: "simple",
  },
  {
    id: "simple-one-link",
    name: "Film + stats + academics",
    audience: "Baseball parents looking for an easier system",
    angle: "One-link benefit",
    eyebrow: "ONE PLAYER. ONE LINK.",
    headline: ["Film.", "Stats.", "Academics.", "One link."],
    supportingText: "Stop sending a different link for every part of the player.",
    image: "/images/marketing-design-3.png",
    primaryText: "Stop sending film, stats, and player information separately. Put the complete baseball profile in one easy-to-share link.",
    linkHeadline: "Everything in one link",
    description: "Build their Diamond Profile free.",
    cta: "Sign Up",
    variant: "one-link",
    series: "simple",
  },
  {
    id: "simple-real-website",
    name: "Give them a real website",
    audience: "Parents of serious baseball players",
    angle: "Product demonstration",
    eyebrow: "NOT ANOTHER PDF",
    headline: ["Give your player", "a real website."],
    supportingText: "Easy to open. Easy to update. Easy to share.",
    image: "/images/marketing-hero.png",
    primaryText: "Give your baseball player a professional website you can update throughout the season. Start free and keep one link wherever you share it.",
    linkHeadline: "Create their player website",
    description: "No design experience needed.",
    cta: "Sign Up",
    variant: "browser",
    series: "simple",
  },
  {
    id: "simple-profile-checklist",
    name: "The complete profile checklist",
    audience: "Parents organizing recruiting materials",
    angle: "Feature clarity",
    eyebrow: "BASEBALL PROFILE CHECKLIST",
    headline: ["Everything", "in its place."],
    supportingText: "A simple home for the information you're already sharing.",
    image: "/images/marketing-design-2.png",
    primaryText: "Film ✓ Stats ✓ Academics ✓ Schedule ✓ Contact information ✓ Give every important detail one organized place to live.",
    linkHeadline: "Build the complete profile",
    description: "Start with the free plan.",
    cta: "Sign Up",
    variant: "checklist",
    series: "simple",
  },
  {
    id: "simple-stop-five-links",
    name: "Stop sending five links",
    audience: "Baseball families currently sharing scattered materials",
    angle: "Before and after",
    eyebrow: "SIMPLIFY THE SHARE",
    headline: ["Stop sending", "five links."],
    supportingText: "Send one Diamond Profile instead.",
    image: "/images/marketing-design-3.png",
    primaryText: "One for film. One for stats. Another for the schedule. Replace the link pile with one complete baseball portfolio.",
    linkHeadline: "One link is easier",
    description: "Build and publish free.",
    cta: "Sign Up",
    variant: "before-after",
    series: "simple",
  },
  {
    id: "simple-whats-the-link",
    name: "What's your player's link?",
    audience: "Parents who want their player prepared",
    angle: "Identity question",
    eyebrow: "BE READY TO SHARE",
    headline: ["What's your", "player's link?"],
    supportingText: "Create one before the next person asks.",
    image: "/images/marketing-design-1.png",
    primaryText: "When someone asks for your player's information, have one clear answer ready. Build their baseball portfolio free with Diamond Profile.",
    linkHeadline: "Claim their Diamond Profile",
    description: "One player. One memorable link.",
    cta: "Sign Up",
    variant: "question",
    series: "simple",
  },
];
