import { Player } from "./types";

export const mockPlayer: Player = {
  slug: "alex-rivera",
  firstName: "Alex",
  lastName: "Rivera",
  position: "Shortstop",
  number: 7,
  team: "Motor City Select",
  league: "Travel Baseball",
  hometown: "Detroit, MI",
  height: "5'11\"",
  weight: "175 lbs",
  bats: "Right",
  throws: "Right",
  birthYear: 2008,
  bio: "A composed middle infielder with quick hands, gap-to-gap power, and a team-first approach. Alex brings consistent energy, strong situational awareness, and a commitment to improving every day.",
  headshotUrl: "/images/headshot-placeholder.svg",
  heroImageUrl: "/images/hero-placeholder.svg",
  currentStats: {
    gamesPlayed: 38,
    battingAverage: 0.347,
    onBasePercentage: 0.429,
    sluggingPercentage: 0.518,
    homeRuns: 5,
    runsBattedIn: 31,
    stolenBases: 14,
    inningsPitched: 0,
    wins: 0,
    losses: 0,
    earnedRunAverage: 0,
    whip: 0,
    strikeoutsPitched: 0,
  },
  seasonHistory: [],
  highlights: [],
  socialLinks: [],
  themeColor: "#ef4444",
  skillsets: [],
  media: [],
  interestsMedia: [],
  trainingVideos: [],
  timeline: [],
};
